---
abstract: 'detect outdated CPAN modules in your environment.'
author:
  - 'Tokuhiro Matsuno'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  Module::Build::Tiny: 0
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: cpan-outdated
provides:
  App::cpanoutdated:
    file: lib/App/cpanoutdated.pm
    version: 0.27
requires:
  CPAN::DistnameInfo: 0.1
  ExtUtils::MakeMaker: 6.56
  IO::Zlib: 0
  LWP: 0
  Module::CoreList: 0
  Module::Metadata: 1.000007
  local::lib: 1.006008
  perl: 5.008001
  version: 0
resources:
  bugtracker: https://github.com/tokuhirom/cpan-outdated/issues
  homepage: https://github.com/tokuhirom/cpan-outdated
  repository: git://github.com/tokuhirom/cpan-outdated.git
version: 0.27
